[package]
name = "fossflow-e2e-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
thirtyfour = "0.34.0"
tokio = { version = "1.47", features = ["full"] }
anyhow = "1.0"

[dev-dependencies]
assert_cmd = "2.0"

[[test]]
name = "basic_load"
path = "tests/basic_load.rs"
